### ISSUE TITLE
Bug on submitting emoji in comment/post

### ISSUE THREAD

**Issue by prabhanshuguptagit** [techspaceusict/techspace-web#3]
![image](https://user-images.githubusercontent.com/16774200/44300192-ac4fec00-a320-11e8-8cf8-5a88e0856453.png)
@Vishal41 @kumarprafful check this one.

**Comment by Vishal41** [comment]
![screenshot from 2018-08-18 20-03-18](https://user-images.githubusercontent.com/20876837/44300272-e5d52700-a321-11e8-8509-93dc9c721e7b.png)
working for me. Can you mention the source of emoji?

**Comment by prabhanshuguptagit** [comment]
Issue solved. Error due to strip_tags.
