### ISSUE TITLE
Form labels not working: Blog add view

### ISSUE THREAD

**Issue by prabhanshuguptagit** [techspaceusict/techspace-web#6]
https://github.com/techspaceusict/techspace-web/blob/82f4c3fb8d779127ed614af4c4c588d111f4308c/blog/forms.py#L21 

Labels are not being rendered the way intended. Currently the default labels are rendered on the view.
@kumarprafful

**Comment by Vishal41** [comment]
@prabhanshuguptagit  I've added the code for changing labels.

**Comment by prabhanshuguptagit** [comment]
Closed in commit 6a970da5bb80ea1ada61027d0bb08cafc5e2df2d
