### ISSUE TITLE
http:// not added in verification email

### ISSUE THREAD

**Issue by kanurag94** [techspaceusict/techspace-web#8]
:/techspace.club/activate/NzA/4$$$

Type link is being generated.

**Comment by kumarprafful** [comment]
@kanurag94 It is not a good option to hardcode the protocol of the website as it keeps on changing. Try passing protocol from the view which is not hardcoded

**Comment by prabhanshuguptagit** [comment]
@kanurag94 Nice find!

**Comment by kanurag94** [comment]
@kumarprafful  I guess my last message is lost
Can you suggest me if we can use 
{% if request.is_secure %}HTTPS{% else %}HTTP{% endif %}
here?

**Comment by kanurag94** [comment]
@prabhanshuguptagit Thanks

**Comment by kumarprafful** [comment]
@kanurag94 Update it in your PR. Nice work.

**Comment by prabhanshuguptagit** [comment]
Commit 2f6929b4a0cebbaa370f1c0e9db873d5d5b3770e
